name: atm1b-docs
channels:
  - conda-forge
dependencies:
  - docutils<0.18
  - fontconfig
  - freetype
  - future
  - graphviz
  - h5py
  - lxml
  - numpy
  - numpydoc
  - pip
  - python>=3.6
  - sphinx
  - sphinx-argparse
  - sphinx_rtd_theme
  - texlive-core
  - pip:
    - ..

